minecraft-server:
  ports:
    - "25565:25565"
    - "25575:25575"
  environment:
    EULA: "TRUE"

  image: itzg/minecraft-server

  volumes:
    - ./data:/data

  container_name: mcserver

  tty: true
  stdin_open: true
  restart: always